### ISSUE TITLE
What is the toolchain integration story?

### ISSUE THREAD

**Issue by fitzgen** [WebAssembly/custom-page-sizes#3]
Two separate-but-related questions:

1. How should toolchains like LLVM expose the Wasm page size to source code?

   * `WASM_PAGE_SIZE` macro?
   * `__builtin_wasm_page_size()` function?

2. How does this integrate with linkers like `lld`?

   * Allow each object to specify its own page size; return link errors if they conflict?
   * Disallow each object to specify its own page size; only allow configuring that in the linker?

cc @tlively

**Comment by alexcrichton** [comment]
One point in favor of doing this as a linker parameter rather than a source macro/function - it'd make distribution of precompiled binaries simpler. For example wasi-libc or the Rust standard library are often distributed precompiled and having to recompile everything with a different page size would be a bit of a bummer.

Implementation-wise what I'd imagine is a new kind of relocation where the page size is generated as `i32.const <max-leb-encoding-of-zero>` and then the relocation fills that in at the end.

**Comment by tlively** [comment]
A new relocation makes sense, or a new linker-defined data symbol (and perhaps a macro that expands to reference that symbol, avoiding the need for recompilation).

Even with linker-controlled page sizes, there's a bit of a source-level back compat problem. Existing libraries that grow the memory (mostly allocators AFAIK) are baking in assumptions that the page size is 64k and will require source modifications to use `__builtin_wasm_page_size()` or `__page_size` or `WASM_PAGE_SIZE` or whatever we end up with.

Once we are confident that this proposal will be adopted, it would make sense to add this builtin/macro/symbol/etc. to clang ASAP and encourage it's use in new code, even if it's always 64k for a while.

**Comment by tlively** [comment]
> Disallow each object to specify its own page size; only allow configuring that in the linker?

Yes, I think this would make the most sense. This is how setting memory size works today.

**Comment by fitzgen** [comment]
> One point in favor of doing this as a linker parameter rather than a source macro/function

Is there a reason a macro or builtin function couldn't be compiled down to exactly that kind of reloc in the object file? Similar to the way that SIMD builtin functions (I presume) get compiled down to particular Wasm SIMD instructions and not to actual function calls.

**Comment by fitzgen** [comment]
@tlively 

> Even with linker-controlled page sizes, there's a bit of a source-level back compat problem. Existing libraries that grow the memory (mostly allocators AFAIK) are baking in assumptions that the page size is 64k and will require source modifications to use `__builtin_wasm_page_size()` or `__page_size` or `WASM_PAGE_SIZE` or whatever we end up with.

Yeah, at that point, by configuring page size in the linker you are effectively saying "I have vetted these object files, they aren't assuming 64KiB, and if I missed anything it is on me now". Essentially, it is now your responsibility at that point. I don't see an alternative to this.

> Once we are confident that this proposal will be adopted, it would make sense to add this builtin/macro/symbol/etc. to clang ASAP and encourage its use in new code, even if it's always 64k for a while.

Big +1 from me.

**Comment by fitzgen** [comment]
FWIW, I think a builtin function or symbol is nicer than a macro, since macros a C/C++ specific thing.

**Comment by alexcrichton** [comment]
Oh that's a good point about getting an abstraction in early even before we change it, I like the idea as well 👍 

> Is there a reason a macro or builtin function couldn't be compiled down to exactly that kind of reloc in the object file?

True! I could rephrase what I was thinking in that if a macro/builtin function is used I don't think it should expand to a constant value that happens to be the current parameter for the current codegen unit. That runs afoul of "makes it harder to ship precompiled binaries".

> or a new linker-defined data symbol (and perhaps a macro that expands to reference that symbol, avoiding the need for recompilation).

Would a linker-defined data symbol mean that the page size would be read from linear memory? If so that might make it a bit harder for wasm compilers themselves to optimize as they'd have to otherwise prove that the memory location never changes. I'm not sure how important optimization will be in this regard, but a relocation modifying an `i32.const` value would make it easier for Wasm optimizing compilers to do their own constant propagation
