### ISSUE TITLE
Binary encoding of custom page sizes

### ISSUE THREAD

**Issue by fitzgen** [WebAssembly/custom-page-sizes#5]
This issue exists to discuss the binary encoding of custom page sizes.

### Relevant Previous Discussion

@fitzgen [said](https://github.com/WebAssembly/design/issues/1512#issuecomment-2021053108)

> We could also encode the page size as `n` in `2^n` which I think would save some LEB encoding bytes.

@alexcrichton [said](https://github.com/WebAssembly/custom-page-sizes/pull/4#discussion_r1542098175)

> Not relevant to this PR, but for the future PR to fill this in I found [this table in the memory64 proposal](https://github.com/WebAssembly/memory64/blob/main/proposals/memory64/Overview.md#binary-format) perhaps a good starting point for determining a binary encoding. (aka pick the next bit in the prefix byte and have it represent a "trailing log2 page size i32" and that may be all that's necessary)

**Comment by alexcrichton** [comment]
To fill out my thinking a bit, I'd propose:

* Memory types start with a single byte
  * Bit 0 of this byte is "is there a max limit"
  * Bit 1 of this byte is "is this memory shared"
  * Bit 2 of this byte is "is this memory 64-bit"
  * [**new**] Bit 3 of this byte is "there is a page size after the limits" 
* If bit 2 is set, then a leb-encoded i64 follows. Otherwise a leb-encoded i32 follows. This is the minimum page size
* If bit 0 is set
  * If bit 2 is set, then a leb-encoded i64 follows. Otherwise a leb-encoded i32 follows. This is the maximum page size
* [**new**] If bit 3 is set, then a leb-encoded i32 follows. This is the log of the page size.

Validation would then ensure that the log(page_size) is included in `[0, 16]`. (or that it's either 0 or 16 depending on how this proposal goes).

Would this actually be the only binary format change necessary? Just memory types?

**Comment by fitzgen** [comment]
@alexcrichton yep, that looks right to me.

> [**new**] If bit 3 is set, then a leb-encoded i32 follows. This is the log of the page size.

Nitpick: I think we could use a raw, unsigned byte here, and not a LEB. I don't expect we will ever want pages larger than `2^255` :joy: 

But I guess it also doesn't really hurt to use LEBs by that same logic, since we won't ever have a second LEB byte in practice anyways. And I guess it gives us some tiny amount of future extensibility/compatibility?

> Would this actually be the only binary format change necessary? Just memory types?

I believe this would be the only change to binary encoding necessary, yes.

**Comment by rossberg** [comment]
FWIW, the alignment on loads/stores is an u32, and that has an even smaller value range.
